# Generated by Django 4.1.6 on 2023-02-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "sku",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=32)),
                ("price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("visits", models.IntegerField(default=0, editable=False)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="products.brand"
                    ),
                ),
            ],
        ),
    ]
